#!/bin/bash

echo "Turn off tracing"
echo 0 > /sys/kernel/debug/tracing/tracing_on
echo 1000 > /sys/kernel/debug/tracing/buffer_size_kb
echo "Redirect trace_pipe to /dev/null"
cat /sys/kernel/debug/tracing/trace_pipe > /dev/null
