#!/usr/bin/python
import os
import sys

KVM_TRACE_PATH="/sys/kernel/debug/tracing/events/kvm"
cmd=["Quit", "KVM All"]
options = ['l', 's']

def show_traces():
	i = 1
	print "----------------------------------"
	prev_item = '{:02}'.format(1)+".[-] "+cmd[i]
	i +=1
	for dirname in os.walk(KVM_TRACE_PATH).next()[1]:
		f = open(KVM_TRACE_PATH+"/"+dirname+"/enable", "r")
		trace_on = f.read()
		f.close()
		trace_on = trace_on.rstrip('\r\n')
		cmd.append(dirname)
		item = '{:02}'.format(i)+".["+trace_on+"] "+dirname

		# Print two columns
		if i%2 == 0:
			print '{0:40}  {1}'.format(prev_item, item)
		else:
			prev_item = item

		i += 1
	print "----------------------------------"

def show_options():
        print ('l. load config')
        print ('s. save config')

	print "----------------------------------"

def handle_option(userInput):

    if userInput in options:
        if userInput == 's':
            print('Saved')
        if userInput == 'l':
            print('Loaded')
    else:
        print('Available options:', options)

def handle_trace(trace_num):

	if trace_num == 0:
		sys.exit(1)

	val = input("Set " + cmd[trace_num] + " to 0 or 1? ")
	if trace_num == 1:
		os.system("echo "+str(val)+" > " + KVM_TRACE_PATH+"/enable")
	else:
		os.system("echo "+str(val)+" > " + KVM_TRACE_PATH+"/"+cmd[trace_num]+"/enable")

def handle_input(userInput):

    try:
           val = int(userInput)
           handle_trace(val)
    except ValueError:
           handle_option(userInput)

while 1:
	show_traces()
        show_options()
	userInput = raw_input("Enter trace number or option: [0 to quit] ")

        print(userInput)

        handle_input(userInput)


