MSG_BOOT = "Boot nvm"
MSG_BOOT_COMPLETED = "Boot nvm completed"
MSG_MIGRATE= "Start migration"
MSG_MIGRATE_COMPLETED= "Migration completed"
MSG_TERMINATE= "Terminate VM"
MSG_TERMINATED= "Terminated VM"
MSG_MIGRATE_CHECK = "Check migration complete on dest"
MSG_MIGRATE_CHECKED = "Migration completed on dest"
